name: Deploy Infrastructure

on:
  push:
    branches:
      - main
defaults:
  run:
    working-directory: ./InfrastructureAsCode     

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.9.0

    - name: Terraform Init
      working-directory: ./InfrastructureAsCode
      run: terraform init

    - name: Terraform Plan
      working-directory: ./InfrastructureAsCode
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: |
        terraform plan -var-file="common.tfvars" \
          -var "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" \
          -var "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          -var "aws_region=${{ secrets.AWS_DEFAULT_REGION }}"

    - name: Terraform Apply
      working-directory: ./InfrastructureAsCode
      run: |
        terraform apply -auto-approve -var-file="common.tfvars" \
          -var "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" \
          -var "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          -var "aws_region=${{ secrets.AWS_DEFAULT_REGION }}"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
